
ccflags-y += -I$(srctree)/drivers/misc/mediatek/i2c/mt6735
ccflags-y += -I$(srctree)/include/mt-plat
ccflags-y += -I$(srctree)/include/mach
ccflags-y += -I$(srctree)/drivers/misc/mediatek/include

obj-$(CONFIG_MTK_I2C) := i2c.o i2c_common.o

